{
    "docs": "https://docs.ansible.com/ansible-core/2.15/dev_guide/testing/sanity/import.html", 
    "results": [
        {
            "message": "The test `ansible-test sanity --test import --python 3.6` [[explain](https://docs.ansible.com/ansible-core/2.15/dev_guide/testing/sanity/import.html)] failed with 1 error:", 
            "output": "plugins/modules/key.py:0:0: traceback: ValueError: collection metadata was not loaded for collection devinsight.semaphore"
        }
    ], 
    "verified": false
}
